export const knowledgeBase = {
  questions: [
    { question: "What is the capital of France?", answer: "Paris" },
    { question: "Who was the first President of the United States?", answer: "George Washington" },
    { question: "What is the boiling point of water?", answer: "100 degrees Celsius" },
    { question: "What is the largest mammal?", answer: "Blue whale" },
    { question: "What is the capital of Japan?", answer: "Tokyo" },
    { question: "Who wrote the play 'Romeo and Juliet'?", answer: "William Shakespeare" },
    { question: "What is the chemical symbol for gold?", answer: "Au" },
    { question: "What is the largest planet in our solar system?", answer: "Jupiter" },
    { question: "Who painted the Mona Lisa?", answer: "Leonardo da Vinci" },
    { question: "What is the longest river in the world?", answer: "Nile" },
    { question: "What is the tallest mountain in the world?", answer: "Mount Everest" },
    { question: "Who invented the telephone?", answer: "Alexander Graham Bell" },
    { question: "What is the currency of China?", answer: "Yuan" },
    { question: "What is the largest ocean on Earth?", answer: "Pacific Ocean" },
    { question: "Who discovered penicillin?", answer: "Alexander Fleming" },
    { question: "What is the capital of Australia?", answer: "Canberra" },
    { question: "What is the square root of 64?", answer: "8" },
    { question: "Who wrote the 'Harry Potter' series?", answer: "J.K. Rowling" },
    { question: "What is the capital of Brazil?", answer: "Brasília" },
    { question: "What is the chemical symbol for oxygen?", answer: "O" },
    { question: "What is the largest desert in the world?", answer: "Sahara" },
    { question: "Who was the first man to walk on the moon?", answer: "Neil Armstrong" },
    { question: "What is the capital of Russia?", answer: "Moscow" },
    { question: "Who discovered gravity?", answer: "Isaac Newton" },
    { question: "What is the national animal of China?", answer: "Giant panda" },
    { question: "What is the largest country in the world?", answer: "Russia" },
    { question: "Who painted the Sistine Chapel ceiling?", answer: "Michelangelo" },
    { question: "What is the chemical symbol for carbon?", answer: "C" },
    { question: "What is the largest bird in the world?", answer: "Ostrich" },
    { question: "Who wrote 'To Kill a Mockingbird'?", answer: "Harper Lee" },
    { question: "What is the capital of South Africa?", answer: "Pretoria" },
    { question: "What is the speed of light in a vacuum?", answer: "299,792 kilometers per second" },
    { question: "Who was the first female Prime Minister of the United Kingdom?", answer: "Margaret Thatcher" },
    { question: "What is the currency of India?", answer: "Rupee" },
    { question: "What is the largest lake in Africa?", answer: "Lake Victoria" },
    { question: "Who discovered America?", answer: "Christopher Columbus" },
    { question: "What is the chemical symbol for silver?", answer: "Ag" },
    { question: "What is the largest continent?", answer: "Asia" },
    { question: "Who wrote 'Pride and Prejudice'?", answer: "Jane Austen" },
    { question: "What is the capital of Canada?", answer: "Ottawa" },
    { question: "What is the square root of 100?", answer: "10" },
    { question: "Who composed the 'Symphony No. 9'?", answer: "Ludwig van Beethoven" },
    { question: "What is the currency of Japan?", answer: "Yen" },
    { question: "What is the highest mountain in Africa?", answer: "Mount Kilimanjaro" },
    { question: "Who painted 'Starry Night'?", answer: "Vincent van Gogh" },
    { question: "What is the chemical symbol for hydrogen?", answer: "H" },
    { question: "What is the largest waterfall in the world?", answer: "Angel Falls" },
    { question: "Who was the first President of the United States to be impeached?", answer: "Andrew Johnson" },
    { question: "What is the capital of Spain?", answer: "Madrid" },
    { question: "What is the largest flower in the world?", answer: "Rafflesia arnoldii" },
    { question: "Who wrote 'The Great Gatsby'?", answer: "F. Scott Fitzgerald" },
    { question: "What is the capital of Italy?", answer: "Rome" },
    // Indian GK questions
    { question: "What is the capital of India?", answer: "New Delhi" },
    { question: "Who is known as the 'Father of the Nation' in India?", answer: "Mahatma Gandhi" },
    { question: "What is the national emblem of India?", answer: "Lion Capital of Ashoka" },
    { question: "Which river is known as the 'Ganga of the South' in India?", answer: "Godavari River" },
    { question: "Who was the first Prime Minister of India?", answer: "Jawaharlal Nehru" },
    { question: "What is the national sport of India?", answer: "Field Hockey" },
    { question: "Which Indian state is known as the 'Land of Five Rivers'?", answer: "Punjab" },
    { question: "Who wrote the Indian national anthem, 'Jana Gana Mana'?", answer: "Rabindranath Tagore" },
    { question: "Which is the largest state in India by area?", answer: "Rajasthan" },
    { question: "Who was the first woman Prime Minister of India?", answer: "Indira Gandhi" },
    { question: "What is the official language of India?", answer: "Hindi" },
    { question: "Which Indian city is known as the 'Pink City'?", answer: "Jaipur" },
    { question: "Who is known as the 'Missile Man of India'?", answer: "APJ Abdul Kalam" },
    { question: "Which is the highest civilian award in India?", answer: "Bharat Ratna" },
    { question: "Who is the current President of India?", answer: "Ram Nath Kovind" },
    { question: "What is the currency of India?", answer: "Indian Rupee" },
    // Casual chat responses
    { question: "What is your favorite food?", answer: "I don't eat, but I think pizza sounds delicious!" },
    { question: "Do you have any pets?", answer: "I don't have pets, but I think cats are adorable." },
    { question: "What's your favorite movie?", answer: "I don't watch movies, but I've heard 'The Matrix' is great!" },
    { question: "Do you like to travel?", answer: "I don't travel, but I think exploring new places sounds exciting!" },
    { question: "What's your favorite book?", answer: "I don't read, but I've heard 'The Hitchhiker's Guide to the Galaxy' is fantastic." },
    { question: "What do you do for fun?", answer: "I chat with people like you and learn new things!" },
    { question: "What's your favorite music genre?", answer: "I don't listen to music, but I think classical music is soothing." },
    { question: "Are you a morning person or a night owl?", answer: "I don't sleep, so I'm available anytime!" },
    { question: "Do you like sports?", answer: "I don't play sports, but I think watching a game can be exciting." },
    { question: "What's your favorite season?", answer: "I don't have a favorite season, but I think each season has its charm." },
    { question: "Do you have any hobbies?", answer: "I don't have hobbies, but I enjoy chatting with you!" },
    { question: "What's your favorite color?", answer: "I don't have a favorite color, but I think blue is nice." },
    { question: "Do you like to cook?", answer: "I don't cook, but I think trying new recipes could be fun!" },
    { question: "What's your dream job?", answer: "I don't have a dream job, but helping people like you is rewarding!" },
    { question: "Are you a fan of any TV shows?", answer: "I don't watch TV, but I've heard 'Friends' is a popular show." },
    { question: "Do you enjoy learning new things?", answer: "I don't learn in the traditional sense, but I enjoy acquiring new information." },
    { question: "What's your opinion on artificial intelligence?", answer: "I think AI has the potential to positively impact many aspects of our lives." },
    { question: "Do you have any siblings?", answer: "I don't have siblings, but I'm here to chat with you!" },
    { question: "What's your favorite thing about chatting with people?", answer: "I enjoy the opportunity to learn and interact with different perspectives." },
    { question: "Do you have a favorite quote?", answer: "I don't have a favorite quote, but 'The only way to do great work is to love what you do.' by Steve Jobs is inspiring." }
  ]
};